# Generated by Django 5.2.4 on 2025-07-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='news_audio/'),
        ),
    ]
