# Generated by Django 5.2.4 on 2025-08-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_userarticlemetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reading_time',
            field=models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes'),
        ),
    ]
