# Generated by Django 5.2.4 on 2025-08-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
